
#@api = http://localhost:3000/api
@api = https://vocabulary-online.herokuapp.com/api




POST {{api}}/auth HTTP/1.1
content-type: application/json

{
	"email": "admin4321@gmail.com",
    "password": "admin4321"
}