
#@api = http://localhost:3000/api

@api = https://vocabulary-online.herokuapp.com/api

@token = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI1ZjFhYmU5NTg4NjkyMzAwMTc2ODQxZWEiLCJyb2xlcyI6WyJBRE1JTiJdLCJmaXJzdE5hbWUiOiJBZG1pbiIsImVtYWlsIjoiYWRtaW40MzIxQGdtYWlsLmNvbSIsImlhdCI6MTU5NTU4ODUwMH0.QN_NEIR_k3mzCcOCenGZnrltNaazmygkioxeboqorP4

GET {{api}}/letters HTTP/1.1

###
GET {{api}}/letters/?letter=А HTTP/1.1

###
###
GET {{api}}/letters/?letter=В HTTP/1.1

###

GET {{api}}/letters/names HTTP/1.1

###

GET {{api}}/letters/2 HTTP/1.1

###

POST {{api}}/letters HTTP/1.1
# content-type: application/json
# x-auth-token: {{token}}

# {
#     "name": "Я",
#     "title": "letter Я"
    
# }

###

PUT {{api}}/letters/1 HTTP/1.1
content-type: application/json
x-auth-token: {{token}}

{
    "name": "А",
    "title": "letter А",
    "words":[
        {
            "name": "some",
            "description": "something"
        },
        {
            "name": "some",
            "description": "something"
        }
    ]
}



